# Generated by Django 6.0.2 on 2026-03-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_procedure',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
